# Generated by Django 3.0.6 on 2020-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0002_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
